export const testimonials = [
  {
    quote:
      "The quality is amazing and the hair feels truly natural from day one.",
    name: "Sarah M.",
    title: "Loyal Customer",
    rating: 5,
  },
  {
    quote:
      "I have tried many brands and this one blends best with my real hair.",
    name: "Jessica L.",
    title: "Professional Stylist",
    rating: 5,
  },
  {
    quote:
      "Customer service via WhatsApp was fast and very helpful.",
    name: "Amara K.",
    title: "Repeat Customer",
    rating: 4,
  },
  {
    quote: "Soft texture, minimal shedding, and easy to style with heat tools.",
    name: "Nadia R.",
    title: "First-Time Buyer",
    rating: 5,
  },
  {
    quote: "The weft quality is strong and my stylist loved working with it.",
    name: "Clara T.",
    title: "Salon Client",
    rating: 4,
  },
  {
    quote: "Color match was better than expected and looked seamless.",
    name: "Maya D.",
    title: "Returning Customer",
    rating: 5,
  },
  {
    quote: "Shipping was quick and packaging looked very premium.",
    name: "Olivia P.",
    title: "Online Shopper",
    rating: 4,
  },
  {
    quote: "The hair stays smooth all day and still looks full after weeks.",
    name: "Hana S.",
    title: "Loyal Customer",
    rating: 5,
  },
  {
    quote: "Great communication and honest guidance on size and color.",
    name: "Lina W.",
    title: "Repeat Customer",
    rating: 4,
  },
  {
    quote: "I used this for a custom wig and the result was beautiful.",
    name: "Arielle G.",
    title: "Wig Maker",
    rating: 5,
  },
  {
    quote: "Very little tangling, even after long wear during events.",
    name: "Rosa V.",
    title: "Event Client",
    rating: 5,
  },
  {
    quote: "The lace front looked natural and comfortable on my scalp.",
    name: "Monica H.",
    title: "Beauty Enthusiast",
    rating: 4,
  },
  {
    quote: "Excellent density and movement, exactly what I wanted.",
    name: "Celine J.",
    title: "Repeat Customer",
    rating: 5,
  },
  {
    quote: "I love the finish. It feels luxurious and photographs well.",
    name: "Dina F.",
    title: "Content Creator",
    rating: 5,
  },
  {
    quote: "Hairline looked natural right out of the box.",
    name: "Rina K.",
    title: "Loyal Customer",
    rating: 4,
  },
  {
    quote: "My order arrived safely and every bundle was consistent.",
    name: "Tessa N.",
    title: "Bulk Buyer",
    rating: 5,
  },
  {
    quote: "No harsh smell and very easy to wash before install.",
    name: "Bianca O.",
    title: "Home Stylist",
    rating: 4,
  },
  {
    quote: "The curl pattern stayed pretty even after a full week.",
    name: "Lara B.",
    title: "Returning Customer",
    rating: 5,
  },
  {
    quote: "Length was accurate and true to what I selected.",
    name: "Nina A.",
    title: "Online Shopper",
    rating: 5,
  },
  {
    quote: "Very good quality for the price and premium feel overall.",
    name: "Keira M.",
    title: "First-Time Buyer",
    rating: 4,
  },
  {
    quote: "I can curl and straighten it without losing softness.",
    name: "Valerie C.",
    title: "Loyal Customer",
    rating: 5,
  },
  {
    quote: "The color options are beautiful and easy to pair.",
    name: "Tania Z.",
    title: "Salon Client",
    rating: 4,
  },
  {
    quote: "Installed it for a wedding and it stayed flawless all day.",
    name: "Elisa Y.",
    title: "Event Client",
    rating: 5,
  },
  {
    quote: "Good volume and soft ends with minimal maintenance.",
    name: "Farah Q.",
    title: "Repeat Customer",
    rating: 4,
  },
  {
    quote: "My stylist said the texture quality is among the best.",
    name: "Joanna U.",
    title: "Salon Client",
    rating: 5,
  },
  {
    quote: "Looks elegant, feels light, and holds style very well.",
    name: "Mira E.",
    title: "Beauty Enthusiast",
    rating: 5,
  },
  {
    quote: "Great product support and accurate recommendations.",
    name: "Nabila I.",
    title: "Returning Customer",
    rating: 4,
  },
  {
    quote: "The straight texture is silky and not stiff at all.",
    name: "Ayesha L.",
    title: "Loyal Customer",
    rating: 5,
  },
  {
    quote: "I received compliments immediately after installation.",
    name: "Ruth X.",
    title: "Repeat Customer",
    rating: 5,
  },
  {
    quote: "No heavy shedding and very easy to brush.",
    name: "Cora S.",
    title: "Online Shopper",
    rating: 4,
  },
  {
    quote: "The bundles are full from top to bottom.",
    name: "Paula R.",
    title: "Wig Maker",
    rating: 5,
  },
  {
    quote: "Worth it for the consistency and premium finish.",
    name: "Dea H.",
    title: "Repeat Customer",
    rating: 4,
  },
  {
    quote: "Very natural shine and soft touch after washing.",
    name: "Sofia T.",
    title: "Loyal Customer",
    rating: 5,
  },
  {
    quote: "Exactly the premium look I wanted for daily wear.",
    name: "Megan G.",
    title: "Returning Customer",
    rating: 5,
  },
  {
    quote: "Good quality control. Every strand feels healthy.",
    name: "Yuni P.",
    title: "Salon Owner",
    rating: 5,
  },
  {
    quote: "Fast delivery and the product matched the photos.",
    name: "Carla D.",
    title: "Repeat Customer",
    rating: 5,
  },
  {
    quote: "The texture blends beautifully with my natural hair.",
    name: "Mona K.",
    title: "Loyal Customer",
    rating: 4,
  },
  {
    quote: "Perfect for custom styles and easy recoloring.",
    name: "Rhea N.",
    title: "Stylist",
    rating: 5,
  },
  {
    quote: "I keep reordering because the quality is consistent.",
    name: "Jenny F.",
    title: "Returning Customer",
    rating: 5,
  },
  {
    quote: "The install was easy and the hair stayed smooth.",
    name: "Dora B.",
    title: "First-Time Buyer",
    rating: 4,
  },
  {
    quote: "My clients request this brand again and again.",
    name: "Karla V.",
    title: "Professional Stylist",
    rating: 5,
  },
  {
    quote: "Beautiful movement, soft touch, and low maintenance.",
    name: "Sinta C.",
    title: "Loyal Customer",
    rating: 4,
  },
  {
    quote: "Great value and a very polished final look.",
    name: "Leona A.",
    title: "Repeat Customer",
    rating: 5,
  },
]

export const testimonialsCount = testimonials.length
