import type { CatalogProduct } from "@/lib/bulk-products"

export const WEFT_PRODUCTS: CatalogProduct[] = [
  {
    name: "Natural Wave",
    slug: "natural-wave-weft",
    price: "$95 - $151",
    image: "/images/texture/natural%20wave%201.png",
    images: ["/images/texture/natural%20wave%202.png"],
    category: "Weft Hair",
    description: "Soft flowing natural wave texture with lightweight movement and a seamless finish.",
  },
  {
    name: "Body Wave",
    slug: "body-wave-weft",
    price: "$98 - $157",
    image: "/images/texture/body%20wave.png",
    category: "Weft Hair",
    description: "Classic body wave for everyday elegance, volume, and easy styling flexibility.",
    tag: "Premium",
  },
  {
    name: "Curly",
    slug: "curly-weft",
    price: "$105 - $168",
    image: "/images/texture/curly%201.png",
    images: ["/images/texture/curly%202.png"],
    category: "Weft Hair",
    description: "Defined curly pattern with natural bounce and fullness for statement looks.",
  },
  {
    name: "Deep Curly",
    slug: "deep-curly-weft",
    price: "$110 - $175",
    image: "/images/texture/deep%20curly.png",
    category: "Weft Hair",
    description: "Dense deep curly texture with rich volume and long-lasting curl definition.",
  },
  {
    name: "Deep Wave",
    slug: "deep-wave-weft",
    price: "$108 - $170",
    image: "/images/texture/deep%20wave.png",
    category: "Weft Hair",
    description: "Deep wave pattern crafted for dramatic texture, softness, and body.",
  },
  {
    name: "Fumi",
    slug: "fumi-weft",
    price: "$125 - $195",
    image: "/images/texture/fumi%201.png",
    images: ["/images/texture/fumi%202.png", "/images/texture/fumi%203.png"],
    category: "Weft Hair",
    description: "Signature fumi texture with premium body and luxury finish.",
    tag: "Best Seller",
  },
  {
    name: "Natural Curly",
    slug: "natural-curly-weft",
    price: "$112 - $176",
    image: "/images/texture/natural%20curly.png",
    category: "Weft Hair",
    description: "Natural curly pattern designed for soft volume and realistic movement.",
  },
  {
    name: "Water Wave",
    slug: "water-wave-weft",
    price: "$107 - $168",
    image: "/images/texture/water%20wave%201.png",
    category: "Weft Hair",
    description: "Water wave texture with smooth S-waves and lightweight wear.",
  },
  {
    name: "Kinky Curl",
    slug: "kinky-curl-weft",
    price: "$118 - $186",
    image: "/images/texture/kinky%20curl.png",
    images: ["/images/texture/kinky%20curl%203.png"],
    category: "Weft Hair",
    description: "Kinky curl texture with maximum fullness and strong curl character.",
  },
  {
    name: "Loose Wave",
    slug: "loose-wave-weft",
    price: "$102 - $162",
    image: "/images/texture/loose%20wave%201.png",
    images: ["/images/texture/loose%20wave%202.png"],
    category: "Weft Hair",
    description: "Relaxed loose wave texture that blends naturally with versatile styling.",
  },
  {
    name: "Jerry Curly",
    slug: "jerry-curly-weft",
    price: "$114 - $180",
    image: "/images/texture/jerry%20curly.png",
    category: "Weft Hair",
    description: "Springy jerry curly pattern with vibrant volume and defined curls.",
  },
  {
    name: "Brazilian Curly",
    slug: "brazilian-curly-weft",
    price: "$120 - $189",
    image: "/images/texture/brazilian%20curly.png",
    category: "Weft Hair",
    description: "Brazilian curly texture with premium softness and rich curl shape.",
    tag: "New",
  },
]
